POST http://localhost:3000/api/profile/register
Content-Type: application/json

{
    "nombre": "Prueba",
    "apellidos": "Nuevo Pc",
    "email": "porfaqueFuncione@gmail.com",
    "password": "pruebaPassword",
    "fechaNacimiento": "Thu, 30 Aug 2001 09:28:21 GMT",
    "rol": "Usuario"
}